### PR TITLE
Add hg

### PR DESCRIPTION
**Pull request by freeformz**

### CODE REVIEW

**Comment by freeformz** [comment]
@potatogopher Can you try out this branch?

``` console
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-go.git#hg
$ git push heroku master
```

**Comment by freeformz** [comment]
For now I've decided to just install hg. Sometime in the future, if this becomes an issue with BZR and SVN as well I will write some code to determine VCS tools needed for the supported vendoring tools and install the needed bits.

**Comment by lstoll** [comment]
:+1:

**Comment by potatogopher** [comment]
@freeformz Everything works great 👍

**Comment by freeformz** [comment]
I'm going to go ahead with merging and releasing this for now (so you can clear the custom BP), but I think I'm going to change things at some point to use a cached version either in the BP or dl a compiled blob from an s3 bucket to reduce external dependencies and build times.

**Comment by RochesterinNYC** [comment]
@freeformz What's the context behind this PR? Why was the hg (and planned BZR) dependency added to the buildpack?

**Comment by freeformz** [comment]
@RochesterinNYC If you include a dep that uses hg, `glide sync` will fail.

**Comment by RochesterinNYC** [comment]
Thanks.

For public reference, issue with the context behind this PR is here: #143

**Comment by freeformz** [comment]
@RochesterinNYC Ahh thanks. Sorry I should have linked it with a "Fixes #143"

**Pull request merged**
