### PR TITLE
Adds go1.19.3, go1.18.8, and go1.17.13

### PR DESCRIPTION
**Pull request by DXTimer**
New versions:

* `1.19.2`, `1.19.3`
* `1.18.4`, `1.18.5`, `1.18.7`, `1.18.8`
* `1.17.11`, `1.17.12`, `1.17.13` 

Default changes:

* `1.19: 1.19.1 => 1.19.3`
* `1.18: 1.18.6 => 1.18.8`
* `1.17: 1.17.10 => 1.17.13`

### CODE REVIEW

**Comment by joshwlewis** [comment]
Thanks @DXTimer. I've taken the liberty to add a few more missing versions to this PR.

**Review by joshwlewis — APPROVED** [review]

**Comment by joshwlewis** [comment]
```
sbin/sync-files.sh golangci-lint-1.45.0-linux-amd64.tar.gz
Getting bucket credentials
Syncing contents of s3://heroku-golang-prod/ to /Users/josh.lewis/code/heroku-buildpack-go/file-cache.
Ensuring the correct versions of all files specified in files.json
Ignored file: golangci-lint-1.45.0-linux-amd64.tar.gz
All files verified, syncing to s3

upload: ./go1.17.13.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.17.13.linux-amd64.tar.gz
upload: ./go1.17.12.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.17.12.linux-amd64.tar.gz
upload: ./go1.17.11.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.17.11.linux-amd64.tar.gz
upload: ./go1.18.5.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.18.5.linux-amd64.tar.gz
upload: ./go1.18.4.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.18.4.linux-amd64.tar.gz
upload: ./go1.18.8.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.18.8.linux-amd64.tar.gz
upload: ./go1.19.2.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.19.2.linux-amd64.tar.gz
upload: ./go1.18.7.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.18.7.linux-amd64.tar.gz
upload: ./go1.19.3.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.19.3.linux-amd64.tar.gz

**Comment by edmorley** [comment]
@joshwlewis I was curious whether this was released or not, so that `cnb-shim` could use the new versions (after seeing [this](https://salesforce-internal.slack.com/archives/C01P6SNBQCW/p1668455109481969)).

I first thought it hadn't been released, since `CHANGELOG.md` says unreleased:
https://github.com/heroku/heroku-buildpack-go/blob/main/CHANGELOG.md#unreleased

...and since there isn't a https://devcenter.heroku.com/changelog entry.

However it looks like it was in fact released to the buildpack registry last week?

```
$ h buildpacks:versions heroku/go | head -n4
Version  Released At               Status
───────  ────────────────────────  ─────────
169      2022-11-09T20:09:14.644Z  published
168      2022-09-08T19:57:23.916Z  published
```

Could you update the readme and post a changelog entry? :-)

**Comment by joshwlewis** [comment]
Yes, this has been released. Sorry for missing those steps.

Changelog update here: https://github.com/heroku/heroku-buildpack-go/pull/504.
Heroku changelog entry here: https://devcenter.heroku.com/changelog-items/2501.

**Pull request merged**
