### PR TITLE
Add go1.13.8 and go1.14

### PR DESCRIPTION
**Pull request by telendt**
Go 1.14 came out yesterday. It would be great to have it, as well as 1.13.8.

### CODE REVIEW

**Comment by telendt** [comment]
Oh, just noticed that @danp opened similar PR (but only for go 1.14) several hours before me in #392. Should I close this one?
(I think it still makes sense to add go 1.13.8.)

**Comment by danp** [comment]
Let's go with this one, thanks! I'll close #392 and run the necessary bit to sync go1.13.8 to S3.

**Comment by danp** [comment]
The sync to S3 has been done.

**Review by kennyp — APPROVED** [review]
LGTM

**Review by owenthereal — APPROVED** [review]

**Comment by jboursiquot-sfdc** [comment]
Ping @heroku/languages

**Comment by AlmogBaku** [comment]
LGTM

**Comment by codedius** [comment]
Hi! Any news when it's done?

**Review by edmorley — APPROVED** [review]

**Review by dzuelke — APPROVED** [review]

**Pull request merged**
