### PR TITLE
Point to internal docs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jkutner** [comment]
Definitely removing the "toolbelt" reference is good, but I'm not sure linking to internal docs is good.

**Comment by freeformzSFDC** [comment]
How else do I enable others to utilize the same deployment instructions?

FWIW: I barely remember that the internal repo exists.

**Comment by ghost** [comment]
cc @jboursiquot-sfdc

**Comment by jkutner** [comment]
I think we should discuss this in an internal channel.

**Comment by ghost** [comment]
@jkutner Done.

**Comment by schneems** [comment]
Where are we with this PR?

**Comment by schneems** [comment]
I fixed a merge conflict on the Changelog. As a side note, I like to link to the PR where a changelog entry comes so people can click through to see the context without having to resort to blame.

**Review by danielleadams — APPROVED** [review]

**Pull request merged**
