### PR TITLE
add LICENSE

### PR DESCRIPTION
**Pull request by freeformz**
Using MIT, which is probably least objectionable to all. I need to get +1s from people who have contributed though. /cc ~~@kr~~ ~~@bmizerany~~ ~~@ryanbrainard~~ ~~@josharian~~ ~~@uhoh-itsmaciek~~ ~~@attilaolah~~ ~~@elithrar~~ ~~@dpiddy~~  ~~@kennethreitz~~ ~~@mbren~~ ~~@cyberdelia~~ ~~@catsby~~  ~~@surma~~ ~~@jonmountjoy~~ ~~@cyx~~ ~~@austinpray~~ ~~@tt~~ ~~@mikehale~~  ~~@mmcgrana~~ @jmazzi @claymccoy @wwy @jszwedko

### CODE REVIEW

**Comment by cyberdelia** [comment]
:+1:

**Comment by surma** [comment]
:+1:

**Comment by ryanbrainard** [comment]
:+1:

**Comment by tt** [comment]
:+1:

**Comment by msakrejda** [comment]
sure

**Comment by austinpray** [comment]
:+1:

**Comment by josharian** [comment]
:+1:

**Comment by elithrar** [comment]
+1

**Comment by danp** [comment]
Indeed!

**Comment by kr** [comment]
+1

**Comment by catsby** [comment]
👍🏼

**Comment by jonmountjoy** [comment]
:+1:

**Comment by mikehale** [comment]
:+1:

**Comment by attilaolah** [comment]
:+1:

**Comment by bmizerany** [comment]
+1

**Comment by mbren** [comment]
+1

**Comment by cyx** [comment]
:+1:

**Comment by kennethreitz** [comment]
:+1:

**Comment by mmcgrana** [comment]
:+1:

**Comment by freeformz** [comment]
I think this has been open long enough and most people have :+1:'d . Merged and closing

**Comment by freeformz** [comment]
Merged as 2daab81cd0e4fd318ceb26d4ae1747a559ef58f6

**Comment by jszwedko** [comment]
:+1:

**Pull request closed without merging**
