### PR TITLE
Simplify publish script

### PR DESCRIPTION
**Pull request by jmorrell**
This simplifies the publishing script by removing the CHANGELOG manipulation. This script required pushing directly to master, which has now been disabled for this repository by turning on branch protection.

### CODE REVIEW

**Comment by jmorrell** [comment]
Sorry @freeformz. Maybe we can get the CHANGELOG updates back via Github actions?

**Review by sowjumn — APPROVED** [review]

**Comment by freeformz** [comment]
FWIW: I am -1 on not adding the Changelog to the release tag: https://github.com/heroku/heroku-buildpack-go/pull/299/files#diff-fdf9292960661b244889134e75c5d303L66

If it's done another way, that's fine, but IMO it's nice to have it reflected in the releases on github.

Also, if branch protection is enabled, releasing will involve a PR to update the changelog.

**Review by freeformz — APPROVED** [review]
But, FWIW: I am -1 on not adding the Changelog to the release tag: https://github.com/heroku/heroku-buildpack-go/pull/299/files#diff-fdf9292960661b244889134e75c5d303L66

If it's done another way, that's fine, but IMO it's nice to have it reflected in the releases on github.

**Comment by jmorrell** [comment]
@freeformz I will look into doing that via actions

**Pull request merged**
