### PR TITLE
Add support for go1.19

### PR DESCRIPTION
**Pull request by CGA1123**
Updates `data.json` and `files.json` to allow `go1.19` support.

### CODE REVIEW

**Review by stonigrl — APPROVED** [review]

**Comment by gaffneyc** [comment]
@edmorley I'm sorry for the ping but any chance of getting 1.19 support merged? It's been almost of month since it was released.

**Comment by edmorley** [comment]
@gaffneyc Hi! I don't maintain this buildpack - @joshwlewis will need to take a look

**Review by edmorley — COMMENTED** [review]
(Switching review requests that need language-owner review to the owner directly)

**Comment by CGA1123** [comment]
Just noticed the workflows have been approved, updated the CHANGELOG.md to make that job happy hopefully 😄

**Comment by CGA1123** [comment]
Pushed additional commit to add in `go1.18.6` and `go1.19.1`, resolving #497.

**Review by joshwlewis — APPROVED** [review]

**Comment by joshwlewis** [comment]
Synced!

```
▹ sbin/sync-files.sh
All files verified, syncing to s3

upload: ./go1.18.6.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.18.6.linux-amd64.tar.gz
upload: ./go1.19.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.19.linux-amd64.tar.gz
upload: ./go1.19.1.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.19.1.linux-amd64.tar.gz
```

**Comment by CGA1123** [comment]
Thanks @joshwlewis 🙇‍♂️!

**Pull request merged**
