### PR TITLE
fix typo in readme

### PR DESCRIPTION
**Pull request by FZambia**
`godep` generates `Godeps` directory with project dependencies

### CODE REVIEW

**Comment by freeformz** [comment]
@FZambia FWIW: I changed this when I rewrote that section as part of https://github.com/heroku/heroku-buildpack-go

**Comment by FZambia** [comment]
Ah, sorry, didn't know about another repo :)

**Comment by freeformz** [comment]
No worries, it's recent and a fork of this one.

**Comment by freeformz** [comment]
Thanks.

Closing since this doesn't merge cleanly and I'm pretty sure I addressed this in a previous commit.

If you run across any others, please PR and we'll merge.

**Pull request closed without merging**
