### PR TITLE
Defaults for GOMAXPROCS

### PR DESCRIPTION
**Pull request by freeformz**
/cc @cyx

### CODE REVIEW

**Comment by cyx** [comment]
LGTM. It seems a bit conservative, but I'm not sure about good tuning defaults for it either.

**Comment by kr** [comment]
Note this is likely to change in Go 1.5 http://golang.org/s/go15gomaxprocs

**Comment by freeformz** [comment]
@kr it will, but I don't think you'd actually want to set GOMAXPROCS to the cpu count for 1x / 2x dynos and the other types are == to the cpu counts of the underlying systems.

**Comment by freeformz** [comment]
I will also likely modulate this based on actual tests and feedback at some point in the future, but this is likely better than the default of 1 (or the new 1.5 defaults) on Heroku.

**Pull request merged**
