### PR TITLE
Add buildpack platform binaries to PATH

### PR DESCRIPTION
**Pull request by mikehale**
This ensures things like godep and jq are available on the `PATH`.

### CODE REVIEW

**Comment by stillinbeta** [comment]
:+1:

**Comment by freeformz** [comment]
But `$build/.profile.d/go.sh` is for use during runtime and the contents of `$buildpack/$plat/bin` isn't available then, so I'm going to close this.

**Comment by mikehale** [comment]
Is `$buildpack/$plat/bin` intended only for use at build time?

**Comment by freeformz** [comment]
@mikehale yes. Take a look at any Go app running on heroku.

**Comment by mikehale** [comment]
TL;DR from chat conversation... `$buildpack/$plat/bin` is in the `$PATH` but that resolves to something like `.build/pack/linux-amd64/bin`, however in some contexts we need an absolute path like `/home/app/.build/pack/linux-amd64/bin`.

**Comment by freeformz** [comment]
AFAICT it's because the platform build environment executes the buildpack with it's full pathname and the way we're using it on the kernel is via calling bin/compile relatively.

When called with the full path it works fine AFAICT.

Double checking now though.

**Pull request closed without merging**
