### PR TITLE
Non-default and private Go Modules proxy support

### PR DESCRIPTION
**Pull request by rykov**
We are now finalizing Go Modules support in Gemfury and would like to allow private dependencies to be used in Heroku projects from both the Gemfury add-on and our regular accounts.

To achieve this, a customer would set the variables GOPROXY, GOPRIVATE, and GONOPROXY for their application as described here: https://gemfury.com/guide/go/install-with-go/

This PR is to propagate these variables from the app config to the build environment directory, and have them be visible to the buildpack's `go build` command.

Related issue:
#377

### CODE REVIEW

**Comment by rykov** [comment]
Bump. Any thoughts on this?

**Comment by edmorley** [comment]
Requested in https://heroku.support/912962

**Comment by rykov** [comment]
For reference, we're looking to enable this functionality for Heroku customer:
https://gemfury.com/guide/go-modules/install-with-go/

Edit: This article is Gemfury-specific, but applies to all non-default Go Modules proxies.

**Comment by danp** [comment]
Thanks for this. We can get this merged if you'd be up for rebasing/merging in current main (especially for #427 to get CI working again).

**Comment by danp** [comment]
Related tests would be welcome, as well, but we/I can come back around after and add those if you're not up for it.

**Comment by rykov** [comment]
@danp Rebased to latest **main**, and I'll put together a test in a bit.

**Comment by rykov** [comment]
@danp And now with the tests. Please let me know if you want access to the Gemfury account here, or if I should upload the source of that module somewhere.

Here's the tested dependency source:
https://gemfury.com/go-test-org/go:git.fury.io%2Fgo-test-org%2Fgotest

**Comment by danp** [comment]
Thanks! If I get the right bits set up for the test in the buildpack's S3 bucket, would you be up for using that? That way the test wouldn't depend on another service and it would keep management of the data with us. It might be even better longer-term to have the tests use some kind of local fake module proxy to verify but we can work that out later.

**Comment by danp** [comment]
Actually, going further: GOPROXY can be set to a filesystem path. Perhaps there's a way to include the module zip/etc in the fixture itself and verify that setting GOPROXY to the path fetches/uses the module as expected?

**Comment by rykov** [comment]
@danp Although here at Gemfury, we're a little bit offended not to carry the same trust as GitHub and GitLab 🤣, we do understand your point of view - using a directory-repo is more stable. I'll update it in a bit.

**Comment by rykov** [comment]
@danp Ok, the repo URL is now `file://...`.

**Comment by danp** [comment]
Awesome, thanks! Looks like one more rebase/merge is in order to fix up CHANGELOG.md.

**Comment by rykov** [comment]
> Awesome, thanks! Looks like one more rebase/merge is in order to fix up CHANGELOG.md.

Done

**Review by danp — APPROVED** [review]

**Review by edmorley — APPROVED** [review]

**Pull request merged**
