### PR TITLE
Update Go version inventory

### PR DESCRIPTION
**Pull request by joshwlewis**
New Versions:

- `1.18.1`
- `1.18.2`
- `1.17.9`
- `1.17.10`

Default changes:

- `1.18: 1.18 => 1.18.2`
- `1.17: 1.17.8 => 1.17.10`

### CODE REVIEW

**Review by edmorley — COMMENTED** [review]
(CI is failing; cancelling review and converting to draft, so I get the email notification when this is ready :-))

**Review by doriskwan — APPROVED** [review]

**Comment by edmorley** [comment]
@joshwlewis This was released in v162, however the tag for that version is missing - would you mind adding it?
https://github.com/heroku/heroku-buildpack-go/tags

The changelog was updated since in #488.

**Comment by edmorley** [comment]
It looks like there is a `make publish` command for this repo (like I have for Python), that uses this script to do both the tagging and publishing (for future releases):
https://github.com/heroku/heroku-buildpack-go/blob/main/sbin/publish.sh

**Comment by joshwlewis** [comment]
@edmorley I see `v162` in the list at https://github.com/heroku/heroku-buildpack-go/tags. I think we're all square after  #488?

**Comment by edmorley** [comment]
@joshwlewis I sorry I missed that - initially there were actually a few GitHub releases (including v161, but not v162), so my message was originally about them, but I decided to delete those handful of releases in favour of just the tags (since most buildpacks only create the tags, and we were already missing lots of releases), and somehow overlooked the fact that the v162 tag did actually exist :-)

**Pull request merged**
