### PR TITLE
Add go1.21.1

### LINKED ISSUE #523: Go 1.21.1 is released!
Go 1.21.0 contains these vulnerabilities: https://github.com/golang/go/issues/62198

### PR DESCRIPTION
**Pull request by kotarou1192**
Closes: #523 
* Add go1.21.1
* go1.21 defaults to go1.21.1

### CODE REVIEW

**Comment by kotarou1192** [comment]
@joshwlewis  Is it possible to be reviewed or get an advice about this please?

**Comment by BlueGhostxxx** [comment]
`kotarou1192:main`

**Comment by BlueGhostxxx** [comment]
> `kotarou1192:main`

**Review by joshwlewis — APPROVED** [review]
Looks good, thanks!

**Comment by joshwlewis** [comment]
```
$ sbin/sync-files.sh
Getting bucket credentials
Syncing contents of s3://heroku-golang-prod/ to /Users/josh.lewis/code/heroku-buildpack-go/file-cache.
Ensuring the correct versions of all files specified in files.json
All files verified, syncing to s3

upload: ./go1.21.1.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.21.1.linux-amd64.tar.gz
```

**Pull request merged**
