### PR TITLE
data: add go1.15.1, go1.14.8

### PR DESCRIPTION
**Pull request by omixen**
go1.15.1, go1.14.8 https://groups.google.com/g/golang-announce/c/8wqlSbkLdPs

### CODE REVIEW

**Comment by omixen** [comment]
@danp can I get a hint on the broken unit test?

**Comment by danp** [comment]
@omixen Thanks for this. Guessing the failures were a flake, are you able to retry the failed jobs?

I did sync the new files to the S3 bucket but that should be unrelated to the failures.

**Comment by danp** [comment]
Actually, sorry, upon further inspection I found the issue. https://github.com/heroku/heroku-buildpack-go/pull/427 should fix it, you'll need to rebase/merge that in once it's merged.

**Comment by omixen** [comment]
@danp that did it. This should be good for review. Thanks for the help!

**Review by danp — APPROVED** [review]

**Review by edmorley — APPROVED** [review]

**Pull request merged**
