### PR TITLE
Add support for Golang 1.20.2 and make it default for 1.20

### PR DESCRIPTION
**Pull request by nestorsalceda**
New Versions:

* `1.20.2`
* `1.20.1`
* `1.19.6`
* `1.19.7`

Default changes:

* `1.20: 1.20 => 1.20.2`
* `1.19: 1.19.5 => 1.19.7`

### CODE REVIEW

**Comment by nestorsalceda** [comment]
Hey @joshwlewis 

Is there something I can do to help with merging this PR?

Thank you!

**Review by joshwlewis — APPROVED** [review]

**Comment by joshwlewis** [comment]
Hey @nestorsalceda - thanks for the PR and the reminder. It looks like we're missing `1.19.6`, `1.19.7`, and `1.20.1` too. I took the liberty of adding  those to your PR.

**Comment by joshwlewis** [comment]
```
$ sbin/sync-files.sh
Getting bucket credentials
Syncing contents of s3://heroku-golang-prod/ to ~/code/heroku-buildpack-go/file-cache.
Ensuring the correct versions of all files specified in files.json
All files verified, syncing to s3

upload: ./go1.20.1.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.20.1.linux-amd64.tar.gz
upload: ./go1.20.2.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.20.2.linux-amd64.tar.gz
upload: ./go1.19.7.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.19.7.linux-amd64.tar.gz
upload: ./go1.19.6.linux-amd64.tar.gz to s3://heroku-golang-prod/go1.19.6.linux-amd64.tar.gz
```

**Comment by nestorsalceda** [comment]
> Hey @nestorsalceda - thanks for the PR and the reminder. It looks like we're missing `1.19.6`, `1.19.7`, and `1.20.1` too. I took the liberty of adding those to your PR.

I will do the next time!

Thank you very much! ❤️

**Pull request merged**
