### PR TITLE
Install github.com/mattes/migrate/cli if specified

### PR DESCRIPTION
**Pull request by freeformz**
Only for govendor ATM. Probably a better way to do this, but this works for now.

### CODE REVIEW

**Comment by freeformz** [comment]
I may actually just start pulling releases from our S3 bucket instead since there are actual releases of mattes/migrate's cli https://github.com/mattes/migrate/releases

**Comment by freeformz** [comment]
Current PR pulls from our S3 bucket's idea of what version of mattes/migrate is released based on the presence of `github.com/heroku/mattes/migrate` in the `heroku.additionalTools` key of `vendor/vendor.json`.

**Comment by bernerdschaefer** [comment]
Tested with the default version and it works great!

**Comment by bernerdschaefer** [comment]
👍

**Pull request merged**
