### PR TITLE
Add go1.10beta2

### PR DESCRIPTION
**Pull request by danp**
https://groups.google.com/forum/#!topic/golang-announce/mfyjMHbaeDA

### CODE REVIEW

**Review by benburkert — APPROVED** [review]

**Review by Xe — APPROVED** [review]

**Comment by freeformz** [comment]
I am syncing the files to the bucket now. Will approve and merge after that.

**Comment by freeformz** [comment]
s3 bucket synced. Once the tests pass I can merge it in.

**Comment by freeformz** [comment]
This forgot the changelog entry.

**Comment by danp** [comment]
Ah sorry, used bcd2bb2adf7abf0afc179f6957ab8140b9c4714d as my guide. Can PR adding an entry if you like.

**Review by amerine — COMMENTED** [review]
NICE, thanks!

**Pull request merged**
