### PR TITLE
[WIP] Add support for dep, the official package management experiment

### PR DESCRIPTION
**Pull request by kyleconroy**
### TODO
- [ ] Write up a better summary and explanation
- [ ] Parse metadata from `Gopkg.toml` instead of my adhoc `heroku.json`
- [ ] Support vendorless repositories by calling `dep ensure`
- [ ] Update the documentation to explain the metadata options
- [ ] Update the test suite to include dep examples

### CODE REVIEW

**Comment by stran12** [comment]
Thanks for creating this ticket! How can I help?

**Comment by freeformz** [comment]
FWIW: I started a branch at gophercon using https://github.com/heroku/tq for querying toml. I just pushed that [branch](https://github.com/heroku/heroku-buildpack-go/tree/dep) (it's not done yet). I think there are parts from both branches that are useful, but I have to spend more time looking into yours.

**Comment by kyleconroy** [comment]
@freeformz @stran12 I need help with a few things. The buildpack downloads binaries from an official Heroku S3 bucket. Can we work on getting tq and dep uploaded to that bucket? Once that happens, testing this will be much easier.

**Comment by kyleconroy** [comment]
@freeformz looking over your branch, I think we should just go with yours. The only thing I noticed is your use of the metadata field in Gopkg.toml. According to the [dep docs](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#metadata), metadata should take the following form:

```
[metadata]
key1 = "value that convey data to other systems"
system1-data = "value that is used by a system"
system2-data = "value that is used by another system"
```

So I think we should use the following values

```
[metadata]
heroku-root-package = "github.com/heroku/fixture"
```

**Comment by stran12** [comment]
@kyleconroy @freeformz Unfortunately, I do not have access to that Heroku S3 bucket neither.

**Comment by freeformz** [comment]
@kyleconroy That is not how it works currently because dep complained. I'll have to update my dep and try again. I hope to take another pass at this later this week

**Comment by brandur** [comment]
Let me know if I can help in some way on this one!

dep is suggesting that although it's still not an official tool, it's an official experiment and [safe for production ready](https://github.com/golang/dep). I was going through all my Go projects this morning and updating their dependency management from govendor to dep before running into this (it was remarkably stable and problem-free otherwise).

**Comment by jmaeso** [comment]
Is this PR still going forward?

**Comment by kyleconroy** [comment]
Sadly I'm still stuck on this PR. For us to add dep support, we need two binaries added to the S3 bucket. @brandur Do you know who has access to do that? I can updated files.json with the appropriate entries, but I need someone to run the sync script

**Comment by jmaeso** [comment]
Maybe @freeformz can help with this point?

**Comment by freeformz** [comment]
@kyleconroy I added the current versions of dep and tq (a small tomlq like tool that I/we wrote) to the s3 bucket and updated files.json. Can you rebase and change this PR to work off those files/tools?

**Comment by freeformz** [comment]
PS: I'm now better positioned and committed to helping you get this merged.

I'm extremely sorry for the delays.

**Comment by kyleconroy** [comment]
Edward,

Thank you so much. Testing this should be much easier now.

**Comment by freeformz** [comment]
@kyleconroy My own branch is coming along: https://github.com/heroku/heroku-buildpack-go/tree/dep

**Comment by freeformz** [comment]
@kyleconroy What do you think about closing this now that #210 is merged?

If some functionality is missing in master now I'll also happily consider a PR.

Thanks!

**Comment by kyleconroy** [comment]
Thanks for getting your branch over the finish line. I ended up not having the time.

**Pull request closed without merging**
